CREATE EXTERNAL TABLE deye_dw_ods.ods_voip (
    `data_type` int,
    `voip_type` string,
    `strsrc_ip` string,
    `strdst_ip` string,
    `strrtp_ip` string,
    `sender_phone` string,
    `receiver_phone` string,
    `third_numbergroup` string,
    `start_time` bigint,
    `end_time` bigint,
    `duration` int,
    `file_path` string,
    `action` string,
    `collect_place` string,
    `protocol` string,
    `capture_time` bigint,
    `insert_time` bigint,
    `data_id` string,
    `insert_day` string,
    `insert_hour` string,
    `insert_min` string,
);