#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2024/1/18 11:34
# @Author  : linkai
# @File    : config_base_info.py
# @Description : 对具体的表字段

# 库名
db_name = "deye_dw_dws"
#表名及字段
dws_theme_app_info = {
    "data_type": str,
    "app_name": str,
    "app_type": str,
    "app_name_alias": str,
    "app_type_alias": str,
    "auth_type": int,
    "auth_account": str,
    "strsrc_ip": str,
    "src_ip_country": str,
    "src_country_hash": str,
    "virtual_account_type": str,
    "virtual_account": str,
    "target_account_type": str,
    "target_account": str,
    "net_action": str,
    "main_account": str,
    "behavior_num": int,
    "attach_md5": str,
    "attach_md5_hash": str,
    "capture_time": int,
    "capture_day": str,
    "capture_hour": int,
    "insert_day": str,
    "insert_hour": str,
}
dws_theme_web_info = {
    "data_type": str,
    "domain": str,
    "auth_type": int,
    "auth_account": str,
    "strsrc_ip": str,
    "src_ip_country": str,
    "src_country_hash": str,
    "strdst_ip": str,
    "dst_ip_country": str,
    "dst_country_hash": str,
    "virtual_account": str,
    "target_account": str,
    "main_account": str,
    "net_action": str,
    "behavior_num": int,
    "attach_md5": str,
    "attach_md5_hash": str,
    "capture_time": int,
    "capture_day": str,
    "capture_hour": int,
    "insert_day": str,
    "insert_hour": str,
}

dws_theme_fix_ip_info = {
    "data_type": str,
    "app_name_alias": str,
    "app_type_alias": str,
    "apps_hash": str,
    "auth_type": int,
    "auth_account": str,
    "strsrc_ip": str,
    "src_ip_country": str,
    "src_country_hash": str,
    "strdst_ip": str,
    "dst_ip_country": str,
    "dst_country_hash": str,
    "virtual_account_type": str,
    "virtual_account": str,
    "virtual_hash": str,
    "net_action": str,
    "main_account": str,
    "behavior_num": int,
    "capture_time": int,
    "capture_day": str,
    "capture_hour": int,
    "insert_day": str,
    "insert_hour": str,
}
dws_theme_block_info = {
    "data_type": str,
    "app_name": str,
    "app_type": str,
    "app_name_alias": str,
    "app_type_alias": str,
    "virtual_account": str,
    "virtual_account_type": str,
    "strsrc_ip": str,
    "strdst_ip": str,
    "src_ip_country": str,
    "dst_ip_country": str,
    "src_ip_city": str,
    "dst_ip_city": str,
    "domain": str,
    "behavior_num": int,
    "earliest_time": int,
    "latest_time": int,
    "insert_day": str,
    "insert_hour": str,
}

dws_element_relation_hardware_feature_info = {
    "data_type": str,
    "auth_type": int,
    "auth_account": str,
    "hardware_type": str,
    "hardware_sign": str,
    "behavior_num": int,
    "earliest_time": int,
    "latest_time": int,
    "insert_day": str,
    "insert_hour": str,
}

dws_element_behavior_connection_info = {
    "data_type": str,
    "auth_type": int,
    "auth_account": str,
    "virtual_account": str,
    "virtual_account_type": str,
    "target_account": str,
    "target_account_type": str,
    "main_account": str,
    "action": str,
    "behavior_num": int,
    "earliest_time": int,
    "latest_time": int,
    "insert_day": str,
    "insert_hour": str,
}

dws_element_behavior_attachment_info ={
    "data_type": str,
    "auth_type": int,
    "auth_account": str,
    "file_id": str,
    "file_path": str,
    "attach_type": str,
    "attach_suffix": str,
    "attach_name": str,
    "attach_size": int,
    "attach_md5": str,
    "attach_md5_hash": str,
    "domain": str,
    "strsrc_ip": str,
    "src_ip_country": str,
    "src_ip_country_hash": str,
    "main_account": str,
    "virtual_account": str,
    "virtual_account_type": str,
    "target_account": str,
    "target_account_type": str,
    "app_name_alias": str,
    "app_type_alias": str,
    "capture_time": int,
    "insert_day": str,
    "insert_hour": str,
}



dwd_behavior_call = {
    "data_id": str,
    "data_type": int,
    "call_type": str,
    "auth_type": str,
    "imsi": str,
    "dst_call_imsi": str,
    "src_number": str,
    "dst_number": str,
    "btisdn": str,
    "start_time": str,
    "end_time": str,
    "continue_time": int,
    "calling_atrribution": str,
    "called_atrribution": str,
    "action": str,
    "file_path": str,
    "sms_text": str,
    "call_id": str,
    "call_flag": int,
    "imei": str,
    "mcc": str,
    "mnc": str,
    "lac": str,
    "cell_id": str,
    "capture_time": str,
    "insert_time": str,
    "insert_hour": str,
    "strsrc_ip": str,
    "strdst_ip": str,
    "ip_type": str,
    "src_country": str,
    "dst_country": str,
    "src_city": str,
    "dst_city": str,
    "phone_number": str,
    "capture_day": str,
    "capture_hour": str,
    "call_tag": int,
    "isp_id": str,
    "src_call_imsi": str,
    "insert_min": str,
    "src_ip_longitude": str,
    "src_ip_latitude": str,
    "dst_ip_longitude": str,
    "dst_ip_latitude": str,
    "insert_day": str
}


dwd_behavior_fax={
  "data_id":str, 
  "strsrc_ip":str, 
  "strdst_ip":str, 
  "src_ip_address":str, 
  "src_ip_country":str, 
  "src_ip_province":str, 
  "src_ip_city":str, 
  "dst_ip_address":str, 
  "dst_ip_country":str, 
  "dst_ip_province":str, 
  "dst_ip_city":str, 
  "src_ip_longitude":str, 
  "src_ip_latitude":str, 
  "dst_ip_longitude":str, 
  "dst_ip_latitude":str, 
  "sender_from_url":str, 
  "receiver_to_url":str, 
  "sender_sip_number":str, 
  "receiver_sip_number":str, 
  "call_id":str, 
  "start_time":str, 
  "end_time":str, 
  "duration":str, 
  "media_type":str, 
  "media_protocol":str, 
  "media_format":str, 
  "file_path":str, 
  "capture_time":str, 
  "capture_day":str, 
  "capture_hour":str, 
  "insert_time":str, 
  "data_type":str,
  "insert_day":str, 
  "insert_hour":str, 
  "insert_min":str
}


dwd_behavior_http = {
  "data_type":str, 
  "child_type":str, 
  "uparea_id":str, 
  "action":str, 
  "src_ipv4":str, 
  "dst_ipv4":str, 
  "src_ipv6":str, 
  "dst_ipv6":str, 
  "src_port_v4":str, 
  "dst_port_v4":str, 
  "src_port_v6":str, 
  "dst_port_v6":str, 
  "src_ip_type":str, 
  "dst_ip_type":str, 
  "src_ip_address":str, 
  "src_ip_country":str, 
  "src_ip_province":str, 
  "src_ip_city":str, 
  "dst_ip_address":str, 
  "dst_ip_country":str, 
  "dst_ip_province":str, 
  "dst_ip_city":str, 
  "src_ip_longitude":str, 
  "src_ip_latitude":str, 
  "dst_ip_longitude":str, 
  "dst_ip_latitude":str, 
  "longitude":str, 
  "latitude":str, 
  "url":str, 
  "domain":str, 
  "sub_domain":str, 
  "auth_type":str, 
  "auth_account":str, 
  "username":str, 
  "password":str, 
  "app_name":str, 
  "app_name_alias":str, 
  "app_type":str, 
  "app_type_alias":str, 
  "isp_id":str, 
  "imsi":str, 
  "imei":str, 
  "mcc":str, 
  "mnc":str, 
  "lac":str, 
  "cell_id":str, 
  "message_id":str, 
  "virtual_account_type":str, 
  "virtual_account":str, 
  "virtual_account_remark":str, 
  "target_account_type":str, 
  "target_account":str, 
  "target_account_remark":str, 
  "other_account_type":str, 
  "other_account":str, 
  "other_account_remark":str, 
  "phone_number":str, 
  "hardware_type":str, 
  "hardware_sign":str, 
  "mac":str, 
  "file_id":str, 
  "file_path":str, 
  "attach_names":str, 
  "attach_sizes":str, 
  "attach_md5s":str, 
  "attach_num":str, 
  "data_type_map":str, 
  "child_type_map":str, 
  "data_id":str, 
  "visit_type":str, 
  "main_account":str, 
  "behavior_num":str, 
  "earliest_time":str, 
  "latest_time":str, 
  "capture_time":str, 
  "capture_day":str, 
  "capture_hour":str, 
  "insert_time":str,
  "insert_day":str, 
  "insert_hour":str, 
  "insert_min":str
}

dwd_behavior_protocol = {
  "data_type":str, 
  "child_type":str, 
  "uparea_id":str, 
  "action":str, 
  "src_ipv4":str, 
  "dst_ipv4":str, 
  "src_ipv6":str, 
  "dst_ipv6":str, 
  "src_port_v4":str, 
  "dst_port_v4":str, 
  "src_port_v6":str, 
  "dst_port_v6":str, 
  "src_ip_type":str, 
  "dst_ip_type":str, 
  "src_ip_address":str, 
  "src_ip_country":str, 
  "src_ip_province":str, 
  "src_ip_city":str, 
  "dst_ip_address":str, 
  "dst_ip_country":str, 
  "dst_ip_province":str, 
  "dst_ip_city":str, 
  "src_ip_longitude":str, 
  "src_ip_latitude":str, 
  "dst_ip_longitude":str, 
  "dst_ip_latitude":str, 
  "longitude":str, 
  "latitude":str, 
  "url":str, 
  "domain":str, 
  "sub_domain":str, 
  "auth_type":str, 
  "auth_account":str, 
  "username":str, 
  "password":str, 
  "app_name":str, 
  "app_name_alias":str, 
  "app_type":str, 
  "app_type_alias":str, 
  "isp_id":str, 
  "imsi":str, 
  "imei":str, 
  "mcc":str, 
  "mnc":str, 
  "lac":str, 
  "cell_id":str, 
  "message_id":str, 
  "virtual_account_type":str, 
  "virtual_account":str, 
  "virtual_account_remark":str, 
  "target_account_type":str, 
  "target_account":str, 
  "target_account_remark":str, 
  "other_account_type":str, 
  "other_account":str, 
  "other_account_remark":str, 
  "phone_number":str, 
  "hardware_type":str, 
  "hardware_sign":str, 
  "mac":str, 
  "file_id":str, 
  "file_path":str, 
  "attach_names":str, 
  "attach_sizes":str, 
  "attach_md5s":str, 
  "attach_num":str, 
  "data_type_map":str, 
  "child_type_map":str, 
  "data_id":str, 
  "visit_type":str, 
  "main_account":str, 
  "behavior_num":str, 
  "earliest_time":str, 
  "latest_time":str, 
  "capture_time":str, 
  "capture_day":str, 
  "capture_hour":str, 
  "insert_time":str,
  "insert_day":str, 
  "insert_hour":str, 
  "insert_min":str
}

dws_protocol_stats_hour = {
    "protocol":str,
    "uparea_id":str,
    "capture_hour":str,
    "capture_day":str,
    "flow":str,
    "insert_hour":str,
    "insert_day":str
}

dws_protocol_stats_week = {
    "protocol":str,
    "uparea_id":str,
    "capture_week":str,
    "capture_hour":str,
    "flow":str,
    "capture_month":str,
    "insert_month":str,
    "insert_week":str
}

dws_app_blocking_up_week = {

    "capture_week":str,
    "capture_hour":str,
    "capture_month":str,
    "user_name":str,
    "user_group":str,
    "app_name":str,
    "app_type":str,
    "flow":str,
    "user_type":str,
    "uparea_id":str,
    "insert_month":str,
    "insert_week":str
}

dws_app_blocking_up_hour = {

    "capture_day":str,
    "capture_hour":str,
    "user_name":str,
    "user_group":str,
    "app_name":str,
    "app_type":str,
    "flow":str,
    "insert_hour":str,
    "user_type":str,
    "uparea_id":str,
    "capture_time":str,
    "insert_day":str
}


dws_app_visit_hour = {

    "capture_day":str,
    "capture_hour":str,
    "user_name":str,
    "user_group":str,
    "app_name":str,
    "app_type":str,
    "flow":str,
    "user_type":str,
    "uparea_id":str,
    "insert_hour":str,
    "capture_time":str,
    "insert_day":str
}

dws_app_visit_hour_top = {

    "capture_hour":str,
    "user_name":str,
    "user_group":str,
    "app_name":str,
    "app_type":str,
    "flow":str,
    "user_type":str,
    "uparea_id":str,
    "capture_day":str,
    "insert_hour":str,
    "insert_day":str
}


dwd_behavior_log = {
  "data_id":str, 
  "data_type":str, 
  "data_type_map":str, 
  "auth_type":str, 
  "auth_account":str, 
  "user_name":str, 
  "user_group":str, 
  "alias":str, 
  "password":str, 
  "virtual_account_type":str, 
  "virtual_account":str, 
  "virtual_account_remark":str, 
  "target_account":str, 
  "target_account_type":str, 
  "target_account_remark":str, 
  "strsrc_ip":str, 
  "strdst_ip":str, 
  "src_port":str, 
  "dst_port":str, 
  "ip_type":str, 
  "src_ip_address":str, 
  "src_ip_country":str, 
  "src_ip_province":str, 
  "src_ip_city":str, 
  "dst_ip_address":str, 
  "dst_ip_country":str, 
  "dst_ip_province":str, 
  "dst_ip_city":str, 
  "src_ip_longitude":str, 
  "src_ip_latitude":str, 
  "dst_ip_longitude":str, 
  "dst_ip_latitude":str, 
  "net_action":str, 
  "action":str, 
  "chat_dir":str, 
  "url":str, 
  "domain":str, 
  "sub_domain":str, 
  "dns":str, 
  "hardware_type":str, 
  "hardware_signature":str, 
  "mac":str, 
  "uparea_id":str, 
  "longitude":str, 
  "latitude":str, 
  "tgdid":str, 
  "is_webapp":str, 
  "app_name":str, 
  "app_type":str, 
  "app_name_alias":str, 
  "app_type_alias":str, 
  "app_devtype":str, 
  "app_devosver":str, 
  "app_devmodel":str, 
  "app_devscreen":str, 
  "app_version":str, 
  "mail_cc":str, 
  "mail_cc_remark":str, 
  "mail_bcc":str, 
  "mail_bcc_remark":str, 
  "imei":str, 
  "imsi":str, 
  "mcc":str, 
  "mnc":str, 
  "lac":str, 
  "cell_id":str, 
  "phone_number":str, 
  "behavior_num":str, 
  "earliest_time":str, 
  "latest_time":str, 
  "capture_time":str, 
  "insert_time":str, 
  "capture_day":str, 
  "capture_hour":str,
  "insert_day":str, 
  "insert_hour":str, 
  "insert_min":str
}



